#!/usr/bin/env python3
"""Emit flash-resident RNN weight array for build.rs (residual_nn_flash feature)."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("npz", type=Path)
    p.add_argument("out_rs", type=Path)
    args = p.parse_args()
    w = np.load(args.npz)["weights"].astype(np.float32)
    if w.shape != (19297,):
        print(f"expected 19297 weights, got {w.shape}", file=sys.stderr)
        return 1
    if not np.all(np.isfinite(w)):
        print("non-finite weights in npz", file=sys.stderr)
        return 1
    lines = [
        "// @generated by export_weights_rs.py — do not edit",
        f"// source: {args.npz}",
        "",
        "#[no_mangle]",
        f"pub static EMBEDDED_RNN_WEIGHTS: [f32; {len(w)}] = [",
    ]
    for i in range(0, len(w), 8):
        chunk = w[i : i + 8]
        lines.append("    " + ", ".join(f"{x:.8e}" for x in chunk) + ",")
    lines.append("];")
    args.out_rs.parent.mkdir(parents=True, exist_ok=True)
    args.out_rs.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out_rs} ({len(w)} f32)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
