#!/usr/bin/env python3
"""Brushless feasibility check for the planned trajectories.

Reads each reference.csv under results/planning_sim/reference/mode*/*/ (already
generated by `planning_sim --export-reference-only`) and checks whether the
planned trajectory fits the Crazyflie 2.1 Brushless (CF21BL) actuator envelope.

Why rescaling is valid (differential flatness):
  - thrust scales LINEARLY with mass         → thrust_bl = thrust_ref * (m_bl / m_ref)
  - body rates omega are MASS-INDEPENDENT    → used as-is
The reference thrust_N column was computed with m_ref = 0.027 kg (planning_sim MASS).

Envelope numbers are from the CF21BL platform defaults + repo notes; refine when
Bitcraze confirms. Run: python3 scripts/brushless_feasibility.py
"""
import csv, glob, math, os

# ── Reference export + brushless envelope ──────────────────────────────────
M_REF          = 0.027    # kg — mass used to compute thrust_N in reference.csv (planning_sim MASS)
M_BL           = 0.0393   # kg — CF2.1 Brushless (weigh your exact config)
G              = 9.81
MAX_THRUST_BL  = 0.80     # N  — total (4 * 0.20 N/motor, THRUST_MAX for CF21BL)
PER_MOTOR_MAX  = 0.20     # N  — per-motor thrust limit
MAX_OMEGA_BL   = 34.0     # rad/s — brushless max body rate

REF_ROOT = os.path.join(os.path.dirname(__file__), "..", "results", "planning_sim", "reference")

def _cols(header):
    idx = {name: i for i, name in enumerate(header)}
    return idx["thrust_N"], idx["omega_x"], idx["omega_y"], idx["omega_z"]

def analyze(path):
    with open(path) as f:
        r = csv.reader(f); h = next(r)
        it, ix, iy, iz = _cols(h)
        peak_thr = 0.0; peak_w = 0.0
        for row in r:
            if len(row) <= iz: continue
            try:
                thr = float(row[it])
                w = math.sqrt(float(row[ix])**2 + float(row[iy])**2 + float(row[iz])**2)
            except ValueError:
                continue
            peak_thr = max(peak_thr, thr); peak_w = max(peak_w, w)
    thr_bl = peak_thr * (M_BL / M_REF)          # rescale thrust to brushless mass
    return thr_bl, peak_w

def main():
    hover_thr = M_BL * G
    print(f"CF2.1 Brushless envelope: total thrust <= {MAX_THRUST_BL:.2f} N "
          f"(T/W = {MAX_THRUST_BL/hover_thr:.2f}), |omega| <= {MAX_OMEGA_BL:.0f} rad/s, "
          f"m = {M_BL*1000:.1f} g  (hover thrust {hover_thr:.3f} N)\n")
    print(f"{'mode/traj':<26}{'peakThr[N]':>11}{'T/W':>7}{'thr%':>7}{'peak|w|':>9}{'w%':>7}  verdict")
    print("-" * 82)
    paths = sorted(glob.glob(os.path.join(REF_ROOT, "mode*", "*", "reference.csv")))
    for p in paths:
        parts = p.split(os.sep)
        tag = f"{parts[-3]}/{parts[-2]}"
        thr_bl, peak_w = analyze(p)
        tw = thr_bl / hover_thr
        thr_u = 100 * thr_bl / MAX_THRUST_BL
        w_u   = 100 * peak_w / MAX_OMEGA_BL
        worst = max(thr_u, w_u)
        verdict = "OK" if worst < 90 else ("MARGINAL" if worst <= 100 else "INFEASIBLE")
        flag = "" if worst < 90 else ("  <-- " + verdict)
        print(f"{tag:<26}{thr_bl:>11.3f}{tw:>7.2f}{thr_u:>6.0f}%{peak_w:>9.1f}{w_u:>6.0f}%  {verdict}{flag}")
    print("\nNote: total-thrust + body-rate are the primary gates; per-motor saturation "
          f"(<= {PER_MOTOR_MAX} N) and torque are secondary. Refine envelope when Bitcraze confirms.")

if __name__ == "__main__":
    main()
