#!/usr/bin/env python3
"""
Spline Figure-8 Flight — min-snap trajectory via Crazyflie high-level commander
=================================================================================
Uploads our minimum-snap figure-8 trajectory (computed by the Rust planner) to
the drone's onboard trajectory memory and executes it using the high-level
commander.

Our trajectory uses the SAME waypoints and segment durations as the professor's
figure8 coefficients (from autonomous_sequence_high_level.py), replanned with
our degree-8 min-snap QP optimizer.

Total path: ±0.92m in x, ±0.45m in y — requires ~2m × 1m clear floor space.

Usage:
    ~/.pyenv/versions/flying_robots/bin/python run_spline_figure8.py
    ~/.pyenv/versions/flying_robots/bin/python run_spline_figure8.py --reps 2

Takeoff/landing use PID (type 1); trajectory uses OOT Rust geometric (type 6).
Requires OOT firmware: cd firmware_app && make cload
"""

import sys
import time
import argparse
import csv
import datetime
import os
import threading

import cflib.crtp
from cflib.crazyflie import Crazyflie
from cflib.crazyflie.log import LogConfig
from cflib.crazyflie.mem import MemoryElement, Poly4D
from cflib.crazyflie.syncCrazyflie import SyncCrazyflie
from cflib.crazyflie.syncLogger import SyncLogger
from cflib.utils import uri_helper

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
DEFAULT_URI = "radio://0/80/2M/E7E7E7E7E7"
HOVER_HEIGHT = 1.0  # m  — matches prof's sequence
SPEED_SCALE = 1.0  # 1.0 = planned speed (durations already tuned to match prof's)
# NOTE: cflib time_scale convention is >1 = slower, <1 = faster.
# We pass 1/SPEED_SCALE so that SPEED_SCALE<1 correctly means slower.
KALMAN_THRESH = 0.001
SCALE = 1.0  # scale down XY to fit small room (~1.3m x 1.4m footprint)
DEFAULT_REPS = 1  # number of figure-8 repetitions to fly by default

# ---------------------------------------------------------------------------
# Figure-8 trajectory — generated by:
#   cargo run --release --bin export_poly4d figure8_match
#
# Format: [duration, cx0..cx7, cy0..cy7, cz0..cz7, cyaw0..cyaw7]
# Planned: same waypoints & durations as prof's figure8, replanned with our
#          degree-8 min-snap QP. Total = 7.28s. All 11 waypoint errors = 0.0000m.
# Path extent: x=[-0.92, +0.92]m, y=[-0.45, +0.45]m.
# ---------------------------------------------------------------------------
figure8_poly4d = [
    [
        1.050000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.920060,
        -0.422403,
        -0.330819,
        0.184887,
        0.000000,
        0.000000,
        -0.000000,
        0.000000,
        -1.744998,
        1.466438,
        0.107645,
        -0.241908,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
    ],
    [
        0.710000,
        0.396058,
        0.894217,
        0.119978,
        -0.586456,
        -0.088417,
        0.767407,
        -0.773189,
        0.263120,
        -0.445604,
        -0.612846,
        0.911715,
        1.039294,
        -0.529370,
        -1.547065,
        1.745710,
        -0.571617,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
    ],
    [
        0.620000,
        0.922409,
        0.425094,
        -0.600250,
        -0.163530,
        -0.012154,
        0.048479,
        0.110009,
        -0.056150,
        -0.291165,
        0.907200,
        0.475613,
        -0.850656,
        0.203289,
        0.237703,
        -0.290271,
        0.089495,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
    ],
    [
        0.700000,
        0.923174,
        -0.445424,
        -0.681107,
        0.226650,
        0.293565,
        -0.024591,
        -0.190025,
        0.072759,
        0.289869,
        0.761427,
        -0.542422,
        -0.353518,
        0.032877,
        -0.064582,
        0.204906,
        -0.075639,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
    ],
    [
        0.560000,
        0.405364,
        -0.824251,
        0.146024,
        0.236002,
        -0.316721,
        -0.076047,
        0.161773,
        -0.039131,
        0.450742,
        -0.405717,
        -0.938657,
        0.192123,
        0.406789,
        0.021473,
        -0.156746,
        0.042205,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
    ],
    [
        0.560000,
        0.000000,
        -0.653540,
        0.006420,
        -0.278385,
        -0.009358,
        0.209809,
        0.006890,
        -0.045898,
        -0.000000,
        -1.022634,
        0.004823,
        0.765421,
        -0.010510,
        -0.227116,
        0.011757,
        0.032847,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
    ],
    [
        0.700000,
        -0.402804,
        -0.819292,
        -0.153336,
        0.224830,
        0.327403,
        -0.067263,
        -0.177646,
        0.076262,
        -0.449354,
        -0.405209,
        0.927436,
        0.184003,
        -0.387313,
        0.024881,
        0.149373,
        -0.070147,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
    ],
    [
        0.620000,
        -0.921641,
        -0.451349,
        0.680038,
        0.234193,
        -0.308640,
        0.000361,
        0.139849,
        -0.058210,
        -0.292459,
        0.755025,
        0.550873,
        -0.343333,
        -0.024645,
        -0.124468,
        -0.087936,
        0.085862,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
    ],
    [
        0.710000,
        -0.923935,
        0.421735,
        0.602634,
        -0.164286,
        -0.084256,
        0.261179,
        -0.536957,
        0.263618,
        0.288570,
        0.912522,
        -0.470936,
        -0.858025,
        -0.016914,
        -0.156197,
        1.086628,
        -0.567817,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
    ],
    [
        1.053185,
        -0.398611,
        0.895363,
        -0.115272,
        -0.585975,
        -0.724664,
        1.764668,
        -1.017567,
        0.182051,
        0.447039,
        -0.609322,
        -0.918168,
        1.034657,
        2.062702,
        -3.428890,
        1.649625,
        -0.237630,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
    ],
]

TRAJ_PLANNED_DURATION = sum(row[0] for row in figure8_poly4d)  # 7.28 s

# ---------------------------------------------------------------------------
# Flight logger — saves CSV for post-flight trajectory analysis
# ---------------------------------------------------------------------------


class FlightLogger:
    """Logs flight state to CSV at 20 Hz for trajectory analysis.

    Usage:
        logger = FlightLogger(cf, name='figure8')
        logger.start()
        logger.mark_traj_start()   # call just before first start_trajectory()
        ...
        logger.stop()              # before landing

    Output: logs/figure8_YYYYMMDD_HHMMSS.csv
    Columns: time_s, x, y, z, vx, vy, vz, roll_deg, pitch_deg, yaw_deg, thrust
    """

    _PERIOD_MS = 50  # 20 Hz
    COLUMNS = [
        "time_s",
        "x",
        "y",
        "z",
        "vx",
        "vy",
        "vz",
        "roll_deg",
        "pitch_deg",
        "yaw_deg",
        "thrust",
    ]

    def __init__(self, cf, name="flight"):
        os.makedirs("logs", exist_ok=True)
        ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        self.path = os.path.join("logs", f"{name}_{ts}.csv")
        self._t0 = None
        self._lock = threading.Lock()
        self._buf = {}
        self._file = open(self.path, "w", newline="")
        self._csv = csv.writer(self._file)
        self._csv.writerow(self.COLUMNS)

        # Config 1: position + attitude (6 floats = 24 bytes, fits in one CRTP packet)
        self._lc1 = LogConfig("FLpos", period_in_ms=self._PERIOD_MS)
        for v in (
            "stateEstimate.x",
            "stateEstimate.y",
            "stateEstimate.z",
            "stabilizer.roll",
            "stabilizer.pitch",
            "stabilizer.yaw",
        ):
            self._lc1.add_variable(v, "float")
        self._lc1.data_received_cb.add_callback(self._cb1)
        cf.log.add_config(self._lc1)

        # Config 2: velocity + thrust (4 floats = 16 bytes)
        self._lc2 = LogConfig("FLvel", period_in_ms=self._PERIOD_MS)
        for v in (
            "stateEstimate.vx",
            "stateEstimate.vy",
            "stateEstimate.vz",
            "stabilizer.thrust",
        ):
            self._lc2.add_variable(v, "float")
        self._lc2.data_received_cb.add_callback(self._cb2)
        cf.log.add_config(self._lc2)

    def start(self):
        self._lc1.start()
        self._lc2.start()

    def mark_traj_start(self):
        """Set t=0. Call just before the first start_trajectory()."""
        with self._lock:
            self._t0 = time.time()

    def _cb1(self, timestamp, data, logconf):
        with self._lock:
            self._buf.update(data)
            if self._t0 is None:
                return
            t = time.time() - self._t0
            s = self._buf
            self._csv.writerow(
                [
                    f"{t:.3f}",
                    s.get("stateEstimate.x", ""),
                    s.get("stateEstimate.y", ""),
                    s.get("stateEstimate.z", ""),
                    s.get("stateEstimate.vx", ""),
                    s.get("stateEstimate.vy", ""),
                    s.get("stateEstimate.vz", ""),
                    s.get("stabilizer.roll", ""),
                    s.get("stabilizer.pitch", ""),
                    s.get("stabilizer.yaw", ""),
                    s.get("stabilizer.thrust", ""),
                ]
            )
            self._file.flush()

    def _cb2(self, timestamp, data, logconf):
        with self._lock:
            self._buf.update(data)

    def stop(self):
        self._lc1.stop()
        self._lc2.stop()
        self._file.close()
        print(f"  [log] Saved: {self.path}")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def upload_trajectory(cf, traj_id, trajectory):
    traj_mem = cf.mem.get_mems(MemoryElement.TYPE_TRAJ)[0]
    traj_mem.trajectory = []

    total = 0.0
    for row in trajectory:
        dur = row[0]
        x = Poly4D.Poly([c * SCALE for c in row[1:9]])
        y = Poly4D.Poly([c * SCALE for c in row[9:17]])
        z = Poly4D.Poly(row[17:25])  # z unscaled — stays flat
        yaw = Poly4D.Poly(row[25:33])  # yaw unscaled
        traj_mem.trajectory.append(Poly4D(dur, x, y, z, yaw))
        total += dur

    ok = traj_mem.write_data_sync()
    if not ok:
        print("Upload failed, aborting!")
        sys.exit(1)
    cf.high_level_commander.define_trajectory(traj_id, 0, len(traj_mem.trajectory))
    return total


def wait_for_kalman(scf, threshold=KALMAN_THRESH):
    print("  Waiting for Kalman estimator to converge...")
    log_cfg = LogConfig(name="KalmanVar", period_in_ms=200)
    log_cfg.add_variable("kalman.varPX", "float")
    log_cfg.add_variable("kalman.varPY", "float")
    log_cfg.add_variable("kalman.varPZ", "float")
    hist_x = [1e3] * 10
    hist_y = [1e3] * 10
    hist_z = [1e3] * 10
    with SyncLogger(scf, log_cfg) as logger:
        for entry in logger:
            d = entry[1]
            hist_x.append(d["kalman.varPX"])
            hist_x.pop(0)
            hist_y.append(d["kalman.varPY"])
            hist_y.pop(0)
            hist_z.append(d["kalman.varPZ"])
            hist_z.pop(0)
            sx = max(hist_x) - min(hist_x)
            sy = max(hist_y) - min(hist_y)
            sz = max(hist_z) - min(hist_z)
            print(f"    spread: x={sx:.5f}  y={sy:.5f}  z={sz:.5f}", end="\r")
            if sx < threshold and sy < threshold and sz < threshold:
                print(f"\n  Converged (spread < {threshold}).")
                return
    print("\n  Warning: Kalman did not converge within log window.")


# ---------------------------------------------------------------------------
# Main flight
# ---------------------------------------------------------------------------


def start_live_log(cf):
    """Persistent async position log — started once, runs for the whole flight."""
    log_cfg = LogConfig(name="FlightLog", period_in_ms=500)
    log_cfg.add_variable("stateEstimate.x", "float")
    log_cfg.add_variable("stateEstimate.y", "float")
    log_cfg.add_variable("stateEstimate.z", "float")
    log_cfg.add_variable("stabilizer.roll", "float")
    log_cfg.add_variable("stabilizer.pitch", "float")
    log_cfg.add_variable("stabilizer.thrust", "float")

    def _cb(timestamp, data, _logconf):
        x = data["stateEstimate.x"]
        y = data["stateEstimate.y"]
        z = data["stateEstimate.z"]
        r = data["stabilizer.roll"]
        p = data["stabilizer.pitch"]
        thr = data["stabilizer.thrust"]
        print(
            f"  [t={timestamp/1000:.1f}s] pos=({x:+.2f},{y:+.2f},{z:+.2f}) "
            f"roll={r:+.1f} pitch={p:+.1f} thrust={thr:.0f}"
        )

    log_cfg.data_received_cb.add_callback(_cb)
    cf.log.add_config(log_cfg)
    log_cfg.start()
    return log_cfg


def fly_figure8(scf, n_reps):
    cf = scf.cf
    hl = cf.high_level_commander
    traj_id = 1

    # Upload before takeoff so it's ready
    print(f"\nUploading figure-8 trajectory ({len(figure8_poly4d)} segments)...")
    duration = upload_trajectory(cf, traj_id, figure8_poly4d)
    actual_s = duration / SPEED_SCALE
    print(
        f"  Planned duration: {duration:.2f} s  |  at SPEED_SCALE={SPEED_SCALE}: {actual_s:.1f} s per rep"
    )
    print(f"  {n_reps} rep(s): {actual_s * n_reps:.1f} s total figure-8 flight")
    print(
        f"  Path extent: x=[-0.92, +0.92]m  y=[-0.45, +0.45]m  — ensure ~2m × 1m clear space"
    )

    # Reset Kalman estimator first (matches prof's order)
    print("Resetting Kalman estimator...")
    cf.param.set_value("kalman.resetEstimation", "1")
    time.sleep(0.1)
    cf.param.set_value("kalman.resetEstimation", "0")
    wait_for_kalman(scf)

    # Arm (required by current firmware before takeoff)
    cf.platform.send_arming_request(True)
    time.sleep(1.0)

    # Takeoff with PID — safe, reliable climb (geometric arming threshold can interfere)
    print("\nSetting controller: PID (type 1) for takeoff")
    cf.param.set_value("stabilizer.controller", "6")
    time.sleep(0.1)

    # Start persistent live log (terminal output) + CSV flight logger
    log_cfg = start_live_log(cf)
    logger = FlightLogger(cf, name="figure8")
    logger.start()

    print(f"\nTakeoff to {HOVER_HEIGHT:.2f} m over 2 s...")
    hl.takeoff(HOVER_HEIGHT, 2.0)
    print("  Waiting 3 s for climb + estimator stabilization...")
    time.sleep(3.0)

    # Switch to OOT geometric controller and let it stabilize at hover height
    # before starting the trajectory (prevents the brief drop on controller switch).
    print("\nSwitching controller: OOT Rust geometric (type 6)")
    # cf.param.set_value("stabilizer.controller", "6")
    print("  Stabilizing hover for 2.5 s...")
    time.sleep(2.5)

    # Execute trajectory (n_reps times; each rep starts from current position)
    for rep in range(1, n_reps + 1):
        print(f"\n--- Rep {rep}/{n_reps}: starting figure-8 ---")
        print(f"  Duration: {actual_s:.1f} s at SPEED_SCALE={SPEED_SCALE}")
        if rep == 1:
            logger.mark_traj_start()  # t=0 at first trajectory start
        hl.start_trajectory(traj_id, 1.0 / SPEED_SCALE, relative_position=True)
        time.sleep(max(0.5, actual_s - 0.05))  # 50ms early → no gap between reps

    # Switch back to PID for safe landing
    print("\nSwitching back to PID (type 1) for landing...")
    # cf.param.set_value("stabilizer.controller", "1")
    time.sleep(0.2)

    print("Landing...")
    logger.stop()
    log_cfg.stop()
    hl.land(0.0, 2.0)
    time.sleep(2.0)
    hl.stop()
    print("Done.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Spline figure-8 flight via HLC (our min-snap coefficients)"
    )
    parser.add_argument(
        "--reps",
        type=int,
        default=DEFAULT_REPS,
        help="Number of figure-8 repetitions (default: DEFAULT_REPS)",
    )
    parser.add_argument(
        "--uri",
        default=None,
        help="Crazyflie URI (default: from environment or radio://0/80/2M/E7E7E7E7E7)",
    )
    args = parser.parse_args()

    uri = args.uri or uri_helper.uri_from_env(default=DEFAULT_URI)
    print(f"Connecting to {uri}...")
    print(f"Reps: {args.reps}  |  SPEED_SCALE: {SPEED_SCALE}")
    print("Takeoff/land: PID  |  Trajectory: OOT Rust geometric (type 6)")

    cflib.crtp.init_drivers()
    with SyncCrazyflie(uri, cf=Crazyflie(rw_cache="./cache")) as scf:
        fly_figure8(scf, n_reps=args.reps)
