#!/usr/bin/env python3
"""
Figure-8 Flight (refactored) — min-snap trajectory via Crazyflie HLC
======================================================================
Refactored version of run_spline_figure8.py using flight_common.py.
Trajectory data and fly function only; all boilerplate lives in flight_common.

Usage:
    ~/.pyenv/versions/flying_robots/bin/python run_figure8.py
    ~/.pyenv/versions/flying_robots/bin/python run_figure8.py --reps 2

Requires OOT firmware: cd firmware_app && make cload
"""

import time
import argparse

import cflib.crtp
from cflib.crazyflie import Crazyflie
from cflib.crazyflie.syncCrazyflie import SyncCrazyflie
from cflib.utils import uri_helper

from flight_common import (
    DEFAULT_URI, HOVER_HEIGHT, KALMAN_THRESH,
    FlightLogger, upload_trajectory,
    wait_for_kalman, start_live_log, reset_kalman,
)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
SPEED_SCALE  = 1.0   # 1.0 = planned speed
SCALE        = 1.0   # XY scale factor
DEFAULT_REPS = 1

# ---------------------------------------------------------------------------
# Figure-8 trajectory — generated by:
#   cargo run --release --bin export_poly4d figure8_match
#
# Format: [duration, cx0..cx7, cy0..cy7, cz0..cz7, cyaw0..cyaw7]
# Total = 7.28s. Path extent: x=[-0.92, +0.92]m, y=[-0.45, +0.45]m.
# ---------------------------------------------------------------------------
figure8_poly4d = [
    [
        1.050000,
        -0.000000, -0.000000, 0.000000, 0.000000, 0.920060, -0.422403, -0.330819, 0.184887,
        0.000000, 0.000000, -0.000000, 0.000000, -1.744998, 1.466438, 0.107645, -0.241908,
        -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
        -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
    ],
    [
        0.710000,
        0.396058, 0.894217, 0.119978, -0.586456, -0.088417, 0.767407, -0.773189, 0.263120,
        -0.445604, -0.612846, 0.911715, 1.039294, -0.529370, -1.547065, 1.745710, -0.571617,
        -0.000000, -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
        -0.000000, -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
    ],
    [
        0.620000,
        0.922409, 0.425094, -0.600250, -0.163530, -0.012154, 0.048479, 0.110009, -0.056150,
        -0.291165, 0.907200, 0.475613, -0.850656, 0.203289, 0.237703, -0.290271, 0.089495,
        -0.000000, -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
        -0.000000, -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
    ],
    [
        0.700000,
        0.923174, -0.445424, -0.681107, 0.226650, 0.293565, -0.024591, -0.190025, 0.072759,
        0.289869, 0.761427, -0.542422, -0.353518, 0.032877, -0.064582, 0.204906, -0.075639,
        -0.000000, -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
        -0.000000, -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
    ],
    [
        0.560000,
        0.405364, -0.824251, 0.146024, 0.236002, -0.316721, -0.076047, 0.161773, -0.039131,
        0.450742, -0.405717, -0.938657, 0.192123, 0.406789, 0.021473, -0.156746, 0.042205,
        -0.000000, -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
        -0.000000, -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
    ],
    [
        0.560000,
        0.000000, -0.653540, 0.006420, -0.278385, -0.009358, 0.209809, 0.006890, -0.045898,
        -0.000000, -1.022634, 0.004823, 0.765421, -0.010510, -0.227116, 0.011757, 0.032847,
        -0.000000, -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
        -0.000000, -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
    ],
    [
        0.700000,
        -0.402804, -0.819292, -0.153336, 0.224830, 0.327403, -0.067263, -0.177646, 0.076262,
        -0.449354, -0.405209, 0.927436, 0.184003, -0.387313, 0.024881, 0.149373, -0.070147,
        -0.000000, -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
        -0.000000, -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
    ],
    [
        0.620000,
        -0.921641, -0.451349, 0.680038, 0.234193, -0.308640, 0.000361, 0.139849, -0.058210,
        -0.292459, 0.755025, 0.550873, -0.343333, -0.024645, -0.124468, -0.087936, 0.085862,
        -0.000000, -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
        -0.000000, -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
    ],
    [
        0.710000,
        -0.923935, 0.421735, 0.602634, -0.164286, -0.084256, 0.261179, -0.536957, 0.263618,
        0.288570, 0.912522, -0.470936, -0.858025, -0.016914, -0.156197, 1.086628, -0.567817,
        -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
        -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
    ],
    [
        1.053185,
        -0.398611, 0.895363, -0.115272, -0.585975, -0.724664, 1.764668, -1.017567, 0.182051,
        0.447039, -0.609322, -0.918168, 1.034657, 2.062702, -3.428890, 1.649625, -0.237630,
        -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
        -0.000000, -0.000000, -0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000,
    ],
]

TRAJ_PLANNED_DURATION = sum(row[0] for row in figure8_poly4d)  # 7.28 s

# ---------------------------------------------------------------------------
# Flight function
# ---------------------------------------------------------------------------


def fly_figure8(scf, n_reps):
    cf = scf.cf
    hl = cf.high_level_commander
    traj_id = 1

    print(f"\nUploading figure-8 trajectory ({len(figure8_poly4d)} segments)...")
    duration = upload_trajectory(cf, traj_id, figure8_poly4d, scale=SCALE)
    actual_s = duration / SPEED_SCALE
    print(f"  Planned: {duration:.2f} s  |  at SPEED_SCALE={SPEED_SCALE}: {actual_s:.1f} s/rep")
    print(f"  {n_reps} rep(s): {actual_s * n_reps:.1f} s total")
    print(f"  Path extent: x=[-0.92, +0.92]m  y=[-0.45, +0.45]m  — ensure ~2m × 1m clear space")

    print("Resetting Kalman estimator...")
    reset_kalman(cf)
    wait_for_kalman(scf)

    cf.platform.send_arming_request(True)
    time.sleep(1.0)

    cf.param.set_value("stabilizer.controller", "6")
    time.sleep(0.1)

    log_cfg = start_live_log(cf)
    logger = FlightLogger(cf, name="figure8")
    logger.start()

    print(f"\nTakeoff to {HOVER_HEIGHT:.2f} m over 2 s...")
    hl.takeoff(HOVER_HEIGHT, 2.0)
    print("  Waiting 3 s for climb + estimator stabilization...")
    time.sleep(3.0)

    print("\nOOT Rust geometric controller active. Stabilizing hover for 2.5 s...")
    time.sleep(2.5)

    for rep in range(1, n_reps + 1):
        print(f"\n--- Rep {rep}/{n_reps}: starting figure-8 ---")
        print(f"  Duration: {actual_s:.1f} s at SPEED_SCALE={SPEED_SCALE}")
        if rep == 1:
            logger.mark_traj_start()
        hl.start_trajectory(traj_id, 1.0 / SPEED_SCALE, relative_position=True)
        time.sleep(max(0.5, actual_s - 0.05))

    print("\nLanding...")
    logger.stop()
    log_cfg.stop()
    hl.land(0.0, 2.0)
    time.sleep(2.0)
    hl.stop()
    print("Done.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Figure-8 flight via HLC")
    parser.add_argument("--reps", type=int, default=DEFAULT_REPS,
                        help="Number of figure-8 repetitions (default: 1)")
    parser.add_argument("--uri", default=None,
                        help="Crazyflie URI (default: radio://0/80/2M/E7E7E7E7E7)")
    args = parser.parse_args()

    uri = args.uri or uri_helper.uri_from_env(default=DEFAULT_URI)
    print(f"Connecting to {uri}...")
    print(f"Reps: {args.reps}  |  SPEED_SCALE: {SPEED_SCALE}")

    cflib.crtp.init_drivers()
    with SyncCrazyflie(uri, cf=Crazyflie(rw_cache="./cache")) as scf:
        fly_figure8(scf, n_reps=args.reps)
