#!/usr/bin/env python3
"""
Fast Figure-8 Flight — properly QP-planned 2× speed via Crazyflie high-level commander
========================================================================================
Same waypoints as run_spline_figure8.py (prof's layout, replanned with our min-snap QP)
but with every segment duration halved.  Properly re-optimised — NOT a time_scale trick.

Generated by:
    cargo run --release --bin export_poly4d fast_figure8

At 2× speed tilt increases (≈48° peak vs ≈12° at 1×), peak thrust rises to ≈0.40 N
(vs ≈0.27 N hover).  Blade flapping, battery sag, and motor model mismatch create
unmodelled torques that INDI rejects automatically — illustrates INDI's advantage.

Usage:
    ~/.pyenv/versions/flying_robots/bin/python run_fast_figure8.py
    ~/.pyenv/versions/flying_robots/bin/python run_fast_figure8.py --reps 2

Requires OOT firmware: cd firmware_app && make cload
"""

import time
import argparse

import cflib.crtp
from cflib.crazyflie import Crazyflie
from cflib.crazyflie.syncCrazyflie import SyncCrazyflie
from cflib.utils import uri_helper

from flight_common import (
    DEFAULT_URI, HOVER_HEIGHT, KALMAN_THRESH,
    FlightLogger, upload_trajectory,
    wait_for_kalman, start_live_log, reset_kalman,
)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
DEFAULT_REPS = 1

# ---------------------------------------------------------------------------
# Fast figure-8 trajectory — generated by:
#   cargo run --release --bin export_poly4d fast_figure8
#
# Same 10 waypoints as run_spline_figure8.py (prof's layout), every segment
# duration halved (3.641 s total vs 7.282 s normal).  QP re-optimised for
# the shorter time window — coefficients differ from the normal figure-8.
#
# Format: [duration, cx0..cx7, cy0..cy7, cz0..cz7, cyaw0..cyaw7]
# Path extent: x=[-0.92, +0.92]m, y=[-0.45, +0.45]m.
# ---------------------------------------------------------------------------
fast_figure8_poly4d = [
    [0.525000,     0.000000,     0.000000,    -0.000000,     0.000000,    14.721231,   -13.518221,   -21.170134,    23.664181,     0.000000,     0.000000,     0.000000,     0.000000,   -27.921423,    46.933582,     6.875987,   -30.956657,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,     0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,     0.000000],
    [0.355000,     0.396058,     1.788435,     0.479912,    -4.691644,    -1.414906,    24.558617,   -49.487778,    33.682228,    -0.445604,    -1.225691,     3.646858,     8.314348,    -8.469375,   -49.510471,   111.736870,   -73.175804,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000],
    [0.310000,     0.922409,     0.850188,    -2.400999,    -1.308238,    -0.194434,     1.550995,     7.041512,    -7.188192,    -0.291165,     1.814400,     1.902450,    -6.805248,     3.252759,     7.605334,   -18.574106,    11.452249,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000],
    [0.350000,     0.923174,    -0.890848,    -2.724426,     1.813201,     4.697038,    -0.786906,   -12.161487,     9.313063,     0.289869,     1.522855,    -2.169687,    -2.828149,     0.526008,    -2.066455,    13.113787,    -9.681414,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000],
    [0.280000,     0.405364,    -1.648502,     0.584094,     1.888018,    -5.067538,    -2.433504,    10.353470,    -5.008752,     0.450742,    -0.811435,    -3.754631,     1.536981,     6.508108,     0.691915,   -10.045361,     5.417976,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000],
    [0.280000,    -0.000000,    -1.307081,     0.025680,    -2.227083,    -0.149873,     6.715198,     0.436747,    -5.870491,    -0.000000,    -2.045268,     0.019294,     6.123369,    -0.167976,    -7.269342,     0.757535,     4.199692,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000],
    [0.350000,    -0.402804,    -1.638585,    -0.613343,     1.798643,     5.238427,    -2.152333,   -11.369637,     9.761742,    -0.449354,    -0.810418,     3.709744,     1.472023,    -6.197081,     0.796588,     9.558938,    -8.978198,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000],
    [0.310000,    -0.921641,    -0.902698,     2.720152,     1.873546,    -4.938235,     0.011555,     8.950330,    -7.450928,    -0.292459,     1.510049,     2.203491,    -2.746664,    -0.394144,    -3.984396,    -5.624136,    10.986733,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000],
    [0.355000,    -0.923935,     0.843471,     2.410536,    -1.314290,    -1.348082,     8.357662,   -34.365170,    33.743046,     0.288570,     1.825044,    -1.883745,    -6.864203,    -0.270524,    -4.999114,    69.546700,   -72.682564,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,     0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,     0.000000],
    [0.526592,    -0.398611,     1.790726,    -0.461090,    -4.687801,   -11.594625,    56.469376,   -65.124260,    23.302589,     0.447039,    -1.218644,    -3.672671,     8.277253,    33.003574,  -109.726562,   105.579918,   -30.419226,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,     0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,     0.000000],
]

TRAJ_PLANNED_DURATION = sum(row[0] for row in fast_figure8_poly4d)  # ≈ 3.641 s


# ---------------------------------------------------------------------------
# Main flight
# ---------------------------------------------------------------------------

def fly_fast_figure8(scf, n_reps):
    cf = scf.cf
    hl = cf.high_level_commander
    traj_id = 1

    print(f"\nUploading fast figure-8 trajectory ({len(fast_figure8_poly4d)} segments)...")
    duration = upload_trajectory(cf, traj_id, fast_figure8_poly4d)
    print(f"  Planned duration: {duration:.3f} s per rep  (QP-planned at 2× speed)")
    print(f"  {n_reps} rep(s): {duration * n_reps:.1f} s total figure-8 flight")
    print(f"  Path extent: x=[-0.92, +0.92]m  y=[-0.45, +0.45]m")

    print("Resetting Kalman estimator...")
    reset_kalman(cf)
    wait_for_kalman(scf)

    cf.platform.send_arming_request(True)
    time.sleep(1.0)

    cf.param.set_value("stabilizer.controller", "6")
    time.sleep(0.1)

    log_cfg = start_live_log(cf)
    logger = FlightLogger(cf, name="fast_figure8")
    logger.start()

    print(f"\nTakeoff to {HOVER_HEIGHT:.2f} m over 2 s...")
    hl.takeoff(HOVER_HEIGHT, 2.0)
    print("  Waiting 3 s for climb + estimator stabilization...")
    time.sleep(3.0)

    print("\nStabilizing hover for 2.5 s...")
    time.sleep(2.5)

    for rep in range(1, n_reps + 1):
        print(f"\n--- Rep {rep}/{n_reps}: starting fast figure-8 ({duration:.2f} s) ---")
        if rep == 1:
            logger.mark_traj_start()
        hl.start_trajectory(traj_id, 1.0, relative_position=True)
        time.sleep(max(0.5, duration - 0.05))

    print("\nLanding...")
    logger.stop()
    log_cfg.stop()
    hl.land(0.0, 2.0)
    time.sleep(2.0)
    hl.stop()
    print("Done.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Fast figure-8 flight — QP-planned at 2× speed via HLC"
    )
    parser.add_argument("--reps", type=int, default=DEFAULT_REPS)
    parser.add_argument("--uri", default=None)
    args = parser.parse_args()

    uri = args.uri or uri_helper.uri_from_env(default=DEFAULT_URI)
    print(f"Connecting to {uri}...")
    print(f"Reps: {args.reps}  |  Duration: {TRAJ_PLANNED_DURATION:.3f} s/rep  "
          f"(QP-planned 2× — no time_scale trick)")
    print("Requires OOT firmware: cd firmware_app && make cload")

    cflib.crtp.init_drivers()
    with SyncCrazyflie(uri, cf=Crazyflie(rw_cache="./cache")) as scf:
        fly_fast_figure8(scf, n_reps=args.reps)
