#!/usr/bin/env python3
"""
Spline Circle Flight — min-snap trajectory via Crazyflie high-level commander
=============================================================================
Uploads a minimum-snap circle trajectory (computed by our Rust planner) to
the drone's onboard trajectory memory and executes it using the high-level
commander.  The drone's onboard polynomial evaluator runs at ~100 Hz, so the
controller receives full position + velocity + acceleration — no radio timing
constraints.

Usage:
    ~/.pyenv/versions/flying_robots/bin/python run_spline_circle.py
    ~/.pyenv/versions/flying_robots/bin/python run_spline_circle.py --laps 2

Takeoff/landing use PID (type 1); trajectory uses OOT Rust geometric (type 6).
Requires OOT firmware: cd firmware_app && make cload
"""

import sys
import time
import argparse
import csv
import datetime
import os
import threading

import cflib.crtp
from cflib.crazyflie import Crazyflie
from cflib.crazyflie.log import LogConfig
from cflib.crazyflie.mem import MemoryElement, Poly4D
from cflib.crazyflie.syncCrazyflie import SyncCrazyflie
from cflib.crazyflie.syncLogger import SyncLogger
from cflib.utils import uri_helper

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
DEFAULT_URI = "radio://0/80/2M/E7E7E7E7E7"
HOVER_HEIGHT = 1.0  # m
SPEED_SCALE = 1.0  # <1 = slower/safer (0.5 = half planned speed)
# NOTE: cflib time_scale convention is >1 = slower, <1 = faster.
# We pass 1/SPEED_SCALE so that SPEED_SCALE<1 correctly means slower.
KALMAN_THRESH = 0.0025
SCALE = 1.0  # scale down XY to fit small room (~1.3m x 1.4m footprint)
DEFAULT_LAPS = 1  # number of laps to fly by default

# ---------------------------------------------------------------------------
# Circle trajectory — generated by:
#   cargo run --release --bin export_poly4d
#
# Format: [duration, cx0..cx7, cy0..cy7, cz0..cz7, cyaw0..cyaw7]
# Planned: r=0.30m, 16 segments × 0.654s, total=10.47s, periodic=True
# Yaw = tangent direction (drone faces direction of travel), unwrapped.
# At SPEED_SCALE=0.5: ~20.9s actual flight per lap
# Circle centered at (0.30, 0) relative to hover; starts & ends at (0,0,0).
# ---------------------------------------------------------------------------
circle_poly4d = [
    [
        0.654498,
        -0.000000,
        0.000000,
        0.054000,
        0.000000,
        -0.001621,
        0.000003,
        0.000016,
        0.000001,
        0.000000,
        0.180000,
        -0.000000,
        -0.010800,
        0.000002,
        0.000190,
        0.000006,
        -0.000004,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        1.570796,
        -0.600000,
        0.000000,
        0.000001,
        -0.000022,
        0.000079,
        -0.000101,
        0.000044,
    ],
    [
        0.654498,
        0.022836,
        0.068883,
        0.049889,
        -0.004133,
        -0.001496,
        0.000073,
        0.000019,
        -0.000001,
        0.114805,
        0.166298,
        -0.020665,
        -0.009978,
        0.000621,
        0.000175,
        -0.000002,
        -0.000004,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        1.178097,
        -0.600000,
        -0.000000,
        -0.000000,
        0.000000,
        -0.000001,
        0.000001,
        -0.000001,
    ],
    [
        0.654498,
        0.087868,
        0.127279,
        0.038184,
        -0.007637,
        -0.001146,
        0.000137,
        0.000015,
        -0.000002,
        0.212132,
        0.127279,
        -0.038184,
        -0.007637,
        0.001144,
        0.000142,
        -0.000019,
        0.000001,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.785398,
        -0.600000,
        0.000000,
        0.000000,
        -0.000003,
        0.000011,
        -0.000014,
        0.000006,
    ],
    [
        0.654498,
        0.185195,
        0.166298,
        0.020665,
        -0.009978,
        -0.000626,
        0.000201,
        -0.000020,
        0.000010,
        0.277164,
        0.068883,
        -0.049889,
        -0.004133,
        0.001493,
        0.000088,
        -0.000036,
        0.000007,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.392699,
        -0.600000,
        -0.000000,
        -0.000000,
        0.000002,
        -0.000009,
        0.000012,
        -0.000005,
    ],
    [
        0.654498,
        0.300000,
        0.180000,
        0.000000,
        -0.010800,
        0.000002,
        0.000186,
        0.000011,
        -0.000006,
        0.300000,
        -0.000000,
        -0.054000,
        0.000000,
        0.001626,
        -0.000022,
        0.000008,
        -0.000012,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -0.000000,
        -0.600000,
        -0.000000,
        0.000000,
        -0.000008,
        0.000032,
        -0.000041,
        0.000018,
    ],
    [
        0.654498,
        0.414805,
        0.166298,
        -0.020665,
        -0.009978,
        0.000631,
        0.000139,
        0.000043,
        -0.000024,
        0.277164,
        -0.068883,
        -0.049889,
        0.004133,
        0.001498,
        -0.000079,
        -0.000012,
        -0.000002,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -0.392699,
        -0.600000,
        0.000000,
        -0.000000,
        -0.000001,
        0.000001,
        -0.000001,
        0.000000,
    ],
    [
        0.654498,
        0.512132,
        0.127279,
        -0.038184,
        -0.007637,
        0.001139,
        0.000161,
        -0.000043,
        0.000012,
        0.212132,
        -0.127279,
        -0.038184,
        0.007637,
        0.001146,
        -0.000140,
        -0.000010,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -0.785398,
        -0.600000,
        -0.000001,
        0.000000,
        0.000006,
        -0.000019,
        0.000023,
        -0.000010,
    ],
    [
        0.654498,
        0.577164,
        0.068883,
        -0.049890,
        -0.004133,
        0.001503,
        0.000051,
        0.000011,
        -0.000013,
        0.114805,
        -0.166298,
        -0.020665,
        0.009978,
        0.000620,
        -0.000182,
        -0.000004,
        0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -1.178097,
        -0.600000,
        0.000001,
        0.000000,
        -0.000005,
        0.000015,
        -0.000018,
        0.000008,
    ],
    [
        0.654498,
        0.600000,
        -0.000000,
        -0.054000,
        0.000000,
        0.001620,
        -0.000001,
        -0.000018,
        -0.000001,
        -0.000000,
        -0.180000,
        0.000000,
        0.010800,
        -0.000003,
        -0.000184,
        -0.000013,
        0.000007,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -1.570796,
        -0.600000,
        -0.000000,
        -0.000000,
        0.000013,
        -0.000045,
        0.000057,
        -0.000025,
    ],
    [
        0.654498,
        0.577164,
        -0.068883,
        -0.049890,
        0.004133,
        0.001492,
        -0.000058,
        -0.000039,
        0.000010,
        -0.114805,
        -0.166298,
        0.020665,
        0.009978,
        -0.000618,
        -0.000188,
        0.000019,
        -0.000003,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -1.963495,
        -0.600000,
        -0.000000,
        -0.000000,
        0.000002,
        -0.000008,
        0.000010,
        -0.000004,
    ],
    [
        0.654498,
        0.512132,
        -0.127279,
        -0.038184,
        0.007637,
        0.001142,
        -0.000126,
        -0.000028,
        0.000008,
        -0.212132,
        -0.127279,
        0.038184,
        0.007637,
        -0.001144,
        -0.000142,
        0.000019,
        -0.000001,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -2.356194,
        -0.600000,
        -0.000000,
        0.000000,
        0.000035,
        -0.000127,
        0.000162,
        -0.000071,
    ],
    [
        0.654498,
        0.414805,
        -0.166298,
        -0.020665,
        0.009978,
        0.000620,
        -0.000180,
        -0.000007,
        0.000001,
        -0.277164,
        -0.068883,
        0.049890,
        0.004133,
        -0.001501,
        -0.000058,
        -0.000002,
        0.000009,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -2.748894,
        -0.600000,
        0.000001,
        -0.000000,
        -0.000012,
        0.000040,
        -0.000050,
        0.000022,
    ],
    [
        0.654498,
        0.300000,
        -0.180000,
        -0.000000,
        0.010800,
        0.000001,
        -0.000196,
        0.000002,
        0.000001,
        -0.300000,
        0.000000,
        0.054000,
        0.000000,
        -0.001619,
        -0.000003,
        0.000024,
        -0.000002,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -3.141593,
        -0.600000,
        -0.000001,
        -0.000001,
        0.000015,
        -0.000053,
        0.000068,
        -0.000030,
    ],
    [
        0.654498,
        0.185195,
        -0.166298,
        0.020665,
        0.009978,
        -0.000621,
        -0.000175,
        0.000002,
        0.000004,
        -0.277164,
        0.068883,
        0.049890,
        -0.004133,
        -0.001504,
        0.000099,
        -0.000013,
        0.000013,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -3.534292,
        -0.600001,
        0.000000,
        0.000001,
        0.000012,
        -0.000043,
        0.000053,
        -0.000023,
    ],
    [
        0.654498,
        0.087868,
        -0.127279,
        0.038184,
        0.007637,
        -0.001145,
        -0.000139,
        0.000015,
        0.000000,
        -0.212132,
        0.127279,
        0.038184,
        -0.007637,
        -0.001146,
        0.000139,
        0.000011,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -3.926991,
        -0.600000,
        0.000001,
        -0.000001,
        0.000014,
        -0.000053,
        0.000068,
        -0.000030,
    ],
    [
        0.654498,
        0.022836,
        -0.068883,
        0.049889,
        0.004133,
        -0.001497,
        -0.000075,
        0.000018,
        0.000000,
        -0.114805,
        0.166298,
        0.020665,
        -0.009978,
        -0.000621,
        0.000183,
        0.000004,
        0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        -0.000000,
        0.000000,
        0.000000,
        0.000000,
        0.000000,
        -4.319690,
        -0.600000,
        -0.000001,
        -0.000000,
        -0.000031,
        0.000117,
        -0.000151,
        0.000066,
    ],
]

TRAJ_PLANNED_DURATION = sum(row[0] for row in circle_poly4d)  # 10.47 s

# ---------------------------------------------------------------------------
# Flight logger — saves CSV for post-flight trajectory analysis
# ---------------------------------------------------------------------------


class FlightLogger:
    """Logs flight state to CSV at 20 Hz for trajectory analysis.

    Usage:
        logger = FlightLogger(cf, name='circle')
        logger.start()
        logger.mark_traj_start()   # call just before first start_trajectory()
        ...
        logger.stop()              # before landing

    Output: logs/circle_YYYYMMDD_HHMMSS.csv
    Columns: time_s, x, y, z, vx, vy, vz, roll_deg, pitch_deg, yaw_deg, thrust
    """

    _PERIOD_MS = 50  # 20 Hz
    COLUMNS = [
        "time_s",
        "x", "y", "z",
        "vx", "vy", "vz",
        "roll_deg", "pitch_deg", "yaw_deg",
        "thrust",
        "gyro_x", "gyro_y", "gyro_z",   # deg/s body-frame angular velocity
    ]

    def __init__(self, cf, name="flight"):
        os.makedirs("logs", exist_ok=True)
        ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        self.path = os.path.join("logs", f"{name}_{ts}.csv")
        self._t0 = None
        self._lock = threading.Lock()
        self._buf = {}
        self._file = open(self.path, "w", newline="")
        self._csv = csv.writer(self._file)
        self._csv.writerow(self.COLUMNS)

        # Config 1: position + attitude (6 floats = 24 bytes, fits in one CRTP packet)
        self._lc1 = LogConfig("FLpos", period_in_ms=self._PERIOD_MS)
        for v in (
            "stateEstimate.x",
            "stateEstimate.y",
            "stateEstimate.z",
            "stabilizer.roll",
            "stabilizer.pitch",
            "stabilizer.yaw",
        ):
            self._lc1.add_variable(v, "float")
        self._lc1.data_received_cb.add_callback(self._cb1)
        cf.log.add_config(self._lc1)

        # Config 2: velocity + thrust (4 floats = 16 bytes)
        self._lc2 = LogConfig("FLvel", period_in_ms=self._PERIOD_MS)
        for v in (
            "stateEstimate.vx",
            "stateEstimate.vy",
            "stateEstimate.vz",
            "stabilizer.thrust",
        ):
            self._lc2.add_variable(v, "float")
        self._lc2.data_received_cb.add_callback(self._cb2)
        cf.log.add_config(self._lc2)

        # Config 3: gyro angular velocity (3 floats = 12 bytes, deg/s)
        self._lc3 = LogConfig("FLgyro", period_in_ms=self._PERIOD_MS)
        for v in ("gyro.x", "gyro.y", "gyro.z"):
            self._lc3.add_variable(v, "float")
        self._lc3.data_received_cb.add_callback(self._cb2)  # same pattern: just update buf
        cf.log.add_config(self._lc3)

    def start(self):
        self._lc1.start()
        self._lc2.start()
        self._lc3.start()

    def mark_traj_start(self):
        """Set t=0. Call just before the first start_trajectory()."""
        with self._lock:
            self._t0 = time.time()

    def _cb1(self, timestamp, data, logconf):
        with self._lock:
            self._buf.update(data)
            if self._t0 is None:
                return
            t = time.time() - self._t0
            s = self._buf
            self._csv.writerow(
                [
                    f"{t:.3f}",
                    s.get("stateEstimate.x", ""),
                    s.get("stateEstimate.y", ""),
                    s.get("stateEstimate.z", ""),
                    s.get("stateEstimate.vx", ""),
                    s.get("stateEstimate.vy", ""),
                    s.get("stateEstimate.vz", ""),
                    s.get("stabilizer.roll", ""),
                    s.get("stabilizer.pitch", ""),
                    s.get("stabilizer.yaw", ""),
                    s.get("stabilizer.thrust", ""),
                    s.get("gyro.x", ""),
                    s.get("gyro.y", ""),
                    s.get("gyro.z", ""),
                ]
            )
            self._file.flush()

    def _cb2(self, timestamp, data, logconf):
        with self._lock:
            self._buf.update(data)

    def stop(self):
        self._lc1.stop()
        self._lc2.stop()
        self._lc3.stop()
        self._file.close()
        print(f"  [log] Saved: {self.path}")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def upload_trajectory(cf, traj_id, trajectory):
    traj_mem = cf.mem.get_mems(MemoryElement.TYPE_TRAJ)[0]
    traj_mem.trajectory = []

    total = 0.0
    for row in trajectory:
        dur = row[0]
        x = Poly4D.Poly([c * SCALE for c in row[1:9]])
        y = Poly4D.Poly([c * SCALE for c in row[9:17]])
        z = Poly4D.Poly(row[17:25])  # z unscaled — stays flat
        yaw = Poly4D.Poly(row[25:33])  # yaw unscaled
        traj_mem.trajectory.append(Poly4D(dur, x, y, z, yaw))
        total += dur

    ok = traj_mem.write_data_sync()
    if not ok:
        print("Upload failed, aborting!")
        sys.exit(1)
    cf.high_level_commander.define_trajectory(traj_id, 0, len(traj_mem.trajectory))
    return total


def wait_for_kalman(scf, threshold=KALMAN_THRESH):
    print("  Waiting for Kalman estimator to converge...")
    log_cfg = LogConfig(name="KalmanVar", period_in_ms=200)
    log_cfg.add_variable("kalman.varPX", "float")
    log_cfg.add_variable("kalman.varPY", "float")
    log_cfg.add_variable("kalman.varPZ", "float")
    hist_x = [1e3] * 10
    hist_y = [1e3] * 10
    hist_z = [1e3] * 10
    with SyncLogger(scf, log_cfg) as logger:
        for entry in logger:
            d = entry[1]
            hist_x.append(d["kalman.varPX"])
            hist_x.pop(0)
            hist_y.append(d["kalman.varPY"])
            hist_y.pop(0)
            hist_z.append(d["kalman.varPZ"])
            hist_z.pop(0)
            sx = max(hist_x) - min(hist_x)
            sy = max(hist_y) - min(hist_y)
            sz = max(hist_z) - min(hist_z)
            print(f"    spread: x={sx:.5f}  y={sy:.5f}  z={sz:.5f}", end="\r")
            if sx < threshold and sy < threshold and sz < threshold:
                print(f"\n  Converged (spread < {threshold}).")
                return
    print("\n  Warning: Kalman did not converge within log window.")


# ---------------------------------------------------------------------------
# Main flight
# ---------------------------------------------------------------------------


def start_live_log(cf):
    """Persistent async position log — started once, runs for the whole flight."""
    log_cfg = LogConfig(name="FlightLog", period_in_ms=500)
    log_cfg.add_variable("stateEstimate.x", "float")
    log_cfg.add_variable("stateEstimate.y", "float")
    log_cfg.add_variable("stateEstimate.z", "float")
    log_cfg.add_variable("stabilizer.roll", "float")
    log_cfg.add_variable("stabilizer.pitch", "float")
    log_cfg.add_variable("stabilizer.thrust", "float")

    def _cb(timestamp, data, _logconf):
        x = data["stateEstimate.x"]
        y = data["stateEstimate.y"]
        z = data["stateEstimate.z"]
        r = data["stabilizer.roll"]
        p = data["stabilizer.pitch"]
        thr = data["stabilizer.thrust"]
        print(
            f"  [t={timestamp/1000:.1f}s] pos=({x:+.2f},{y:+.2f},{z:+.2f}) "
            f"roll={r:+.1f} pitch={p:+.1f} thrust={thr:.0f}"
        )

    log_cfg.data_received_cb.add_callback(_cb)
    cf.log.add_config(log_cfg)
    log_cfg.start()
    return log_cfg


def fly_circle(scf, n_laps):
    cf = scf.cf
    hl = cf.high_level_commander
    traj_id = 1

    # Upload before takeoff so it's ready
    print(f"\nUploading circle trajectory ({len(circle_poly4d)} segments)...")
    duration = upload_trajectory(cf, traj_id, circle_poly4d)
    actual_s = duration / SPEED_SCALE
    print(
        f"  Planned duration: {duration:.2f} s  |  at SPEED_SCALE={SPEED_SCALE}: {actual_s:.1f} s per lap"
    )
    print(f"  {n_laps} lap(s): {actual_s * n_laps:.1f} s total flight")

    # Reset Kalman estimator first (matches prof's order)
    print("Resetting Kalman estimator...")
    cf.param.set_value("kalman.resetEstimation", "1")
    time.sleep(0.1)
    cf.param.set_value("kalman.resetEstimation", "0")
    wait_for_kalman(scf)

    # Arm (required by current firmware before takeoff)
    cf.platform.send_arming_request(True)
    time.sleep(1.0)

    # Takeoff with PID — safe, reliable climb
    print("\nSetting controller: PID (type 1) for takeoff")
    cf.param.set_value("stabilizer.controller", "6")
    time.sleep(0.1)

    # Start persistent live log (terminal output) + CSV flight logger
    log_cfg = start_live_log(cf)
    logger = FlightLogger(cf, name="circle")
    logger.start()

    print(f"\nTakeoff to {HOVER_HEIGHT:.2f} m over 2 s...")
    hl.takeoff(HOVER_HEIGHT, 2.0)
    print("  Waiting 3 s for climb + estimator stabilization...")
    time.sleep(3.0)

    # Switch to OOT geometric controller and let it stabilize at hover height
    # before starting the trajectory (prevents the brief drop on controller switch).
    print("\nSwitching controller: OOT Rust geometric (type 6)")
    # cf.param.set_value("stabilizer.controller", "6")
    print("  Stabilizing hover for 2.5 s...")
    time.sleep(2.5)

    # Execute trajectory (n_laps times; each lap starts from current position)
    for lap in range(1, n_laps + 1):
        print(f"\n--- Lap {lap}/{n_laps}: starting trajectory ---")
        print(f"  Duration: {actual_s:.1f} s at SPEED_SCALE={SPEED_SCALE}")
        if lap == 1:
            logger.mark_traj_start()  # t=0 at first trajectory start
        hl.start_trajectory(traj_id, 1.0 / SPEED_SCALE, relative_position=True)
        time.sleep(max(0.5, actual_s - 0.05))  # 50ms early → no gap between laps

    # Switch back to PID for safe landing
    print("\nSwitching back to PID (type 1) for landing...")
    # cf.param.set_value("stabilizer.controller", "1")
    time.sleep(0.2)

    print("Landing...")
    logger.stop()
    log_cfg.stop()
    hl.land(0.0, 2.0)
    time.sleep(2.0)
    hl.stop()
    print("Done.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Spline circle flight via HLC")
    parser.add_argument(
        "--laps",
        type=int,
        default=DEFAULT_LAPS,
        help="Number of laps to fly (default: DEFAULT_LAPS)",
    )
    parser.add_argument(
        "--uri",
        default=None,
        help="Crazyflie URI (default: from environment or radio://0/80/2M/E7E7E7E7E7)",
    )
    args = parser.parse_args()

    uri = args.uri or uri_helper.uri_from_env(default=DEFAULT_URI)
    print(f"Connecting to {uri}...")
    print(f"Laps: {args.laps}  |  SPEED_SCALE: {SPEED_SCALE}")
    print("Takeoff/land: PID  |  Trajectory: OOT Rust geometric (type 6)")

    cflib.crtp.init_drivers()
    with SyncCrazyflie(uri, cf=Crazyflie(rw_cache="./cache")) as scf:
        fly_circle(scf, n_laps=args.laps)
