#!/usr/bin/env python3
"""
Spline Circle Flight — min-snap trajectory via Crazyflie high-level commander
=============================================================================
Uploads a minimum-snap circle trajectory (computed by our Rust planner) to
the drone's onboard trajectory memory and executes it using the high-level
commander.  The drone's onboard polynomial evaluator runs at ~100 Hz, so the
controller receives full position + velocity + acceleration — no radio timing
constraints.

Usage:
    ~/.pyenv/versions/flying_robots/bin/python run_spline_circle.py
    ~/.pyenv/versions/flying_robots/bin/python run_spline_circle.py --controller 6
    ~/.pyenv/versions/flying_robots/bin/python run_spline_circle.py --laps 2

The --controller flag selects:
    6  OOT Rust geometric controller (default — requires updated firmware)
    2  Mellinger firmware controller  (fallback)
"""

import sys
import time
import argparse

import cflib.crtp
from cflib.crazyflie import Crazyflie
from cflib.crazyflie.log import LogConfig
from cflib.crazyflie.mem import MemoryElement, Poly4D
from cflib.crazyflie.syncCrazyflie import SyncCrazyflie
from cflib.crazyflie.syncLogger import SyncLogger
from cflib.utils import uri_helper

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
DEFAULT_URI    = "radio://0/80/2M/E7E7E7E7E7"
HOVER_HEIGHT   = 0.25   # m
SPEED_SCALE    = 0.5    # <1 = slower/safer (0.5 = half planned speed)
KALMAN_THRESH  = 0.0025

# ---------------------------------------------------------------------------
# Circle trajectory — generated by:
#   cargo run --release --bin export_poly4d
#
# Format: [duration, cx0..cx7, cy0..cy7, cz0..cz7, cyaw0..cyaw7]
# Planned: r=0.30m, 8 segments × 1.309s, total=10.47s, periodic=True
# At SPEED_SCALE=0.5: ~20.9s actual flight per lap
# Circle centered at (0.30, 0) relative to hover; starts & ends at (0,0,0).
# periodic=True: derivatives wrap smoothly at the junction — true circle shape.
# Initial tangential velocity ≈ r·ω·SPEED_SCALE = 0.30·0.6·0.5 = 0.09 m/s.
# ---------------------------------------------------------------------------
circle_poly4d = [
    [1.308997,     0.000000,     0.000000,     0.054001,    -0.000000,    -0.001621,     0.000000,     0.000020,    -0.000001,    -0.000000,     0.180000,     0.000000,    -0.010800,    -0.000000,     0.000194,    -0.000000,    -0.000002,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000],
    [1.308997,     0.087868,     0.127279,     0.038184,    -0.007636,    -0.001146,     0.000137,     0.000014,    -0.000002,     0.212132,     0.127279,    -0.038184,    -0.007636,     0.001146,     0.000137,    -0.000014,    -0.000001,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000],
    [1.308997,     0.300000,     0.180000,    -0.000000,    -0.010800,     0.000000,     0.000194,    -0.000000,    -0.000002,     0.300000,    -0.000000,    -0.054001,     0.000000,     0.001621,    -0.000000,    -0.000020,     0.000001,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000],
    [1.308997,     0.512132,     0.127279,    -0.038184,    -0.007636,     0.001146,     0.000137,    -0.000014,    -0.000001,     0.212132,    -0.127279,    -0.038184,     0.007636,     0.001146,    -0.000137,    -0.000014,     0.000002,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000],
    [1.308997,     0.600000,    -0.000000,    -0.054001,     0.000000,     0.001621,    -0.000000,    -0.000020,     0.000001,    -0.000000,    -0.180000,     0.000000,     0.010800,     0.000000,    -0.000194,     0.000000,     0.000002,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000],
    [1.308997,     0.512132,    -0.127279,    -0.038184,     0.007636,     0.001146,    -0.000137,    -0.000014,     0.000002,    -0.212132,    -0.127279,     0.038184,     0.007636,    -0.001146,    -0.000137,     0.000014,     0.000001,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000],
    [1.308997,     0.300000,    -0.180000,    -0.000000,     0.010800,     0.000000,    -0.000194,    -0.000000,     0.000002,    -0.300000,     0.000000,     0.054001,    -0.000000,    -0.001621,     0.000000,     0.000020,    -0.000001,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000],
    [1.308997,     0.087868,    -0.127279,     0.038184,     0.007636,    -0.001146,    -0.000137,     0.000014,     0.000001,    -0.212132,     0.127279,     0.038184,    -0.007636,    -0.001146,     0.000137,     0.000014,    -0.000002,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000,    -0.000000,    -0.000000,    -0.000000,    -0.000000,     0.000000,     0.000000,     0.000000,     0.000000],
]

TRAJ_PLANNED_DURATION = sum(row[0] for row in circle_poly4d)  # 10.47 s

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def upload_trajectory(cf, traj_id, trajectory):
    traj_mem = cf.mem.get_mems(MemoryElement.TYPE_TRAJ)[0]
    traj_mem.trajectory = []
    total = 0.0
    for row in trajectory:
        dur = row[0]
        traj_mem.trajectory.append(
            Poly4D(
                dur,
                Poly4D.Poly(row[1:9]),    # x coefficients
                Poly4D.Poly(row[9:17]),   # y coefficients
                Poly4D.Poly(row[17:25]),  # z coefficients (constant altitude)
                Poly4D.Poly(row[25:33]),  # yaw coefficients (constant heading)
            )
        )
        total += dur
    ok = traj_mem.write_data_sync()
    if not ok:
        raise RuntimeError("Trajectory upload failed")
    cf.high_level_commander.define_trajectory(traj_id, 0, len(traj_mem.trajectory))
    return total


def wait_for_kalman(scf, threshold=KALMAN_THRESH):
    print("  Waiting for Kalman estimator to converge...")
    log_cfg = LogConfig(name="KalmanVar", period_in_ms=200)
    log_cfg.add_variable("kalman.varPX", "float")
    log_cfg.add_variable("kalman.varPY", "float")
    log_cfg.add_variable("kalman.varPZ", "float")
    hist_x = [1e3] * 10
    hist_y = [1e3] * 10
    hist_z = [1e3] * 10
    with SyncLogger(scf, log_cfg) as logger:
        for entry in logger:
            d = entry[1]
            hist_x.append(d["kalman.varPX"]); hist_x.pop(0)
            hist_y.append(d["kalman.varPY"]); hist_y.pop(0)
            hist_z.append(d["kalman.varPZ"]); hist_z.pop(0)
            sx = max(hist_x) - min(hist_x)
            sy = max(hist_y) - min(hist_y)
            sz = max(hist_z) - min(hist_z)
            print(f"    spread: x={sx:.5f}  y={sy:.5f}  z={sz:.5f}", end="\r")
            if sx < threshold and sy < threshold and sz < threshold:
                print(f"\n  Converged (spread < {threshold}).")
                return
    print("\n  Warning: Kalman did not converge within log window.")


# ---------------------------------------------------------------------------
# Main flight
# ---------------------------------------------------------------------------

def fly_circle(scf, n_laps, controller):
    cf = scf.cf
    hl = cf.high_level_commander
    traj_id = 1

    # Upload before takeoff so it's ready
    print(f"\nUploading circle trajectory ({len(circle_poly4d)} segments)...")
    duration = upload_trajectory(cf, traj_id, circle_poly4d)
    actual_s = duration / SPEED_SCALE
    print(f"  Planned duration: {duration:.2f} s  |  at SPEED_SCALE={SPEED_SCALE}: {actual_s:.1f} s per lap")
    print(f"  {n_laps} lap(s): {actual_s * n_laps:.1f} s total flight")

    # Set controller
    ctrl_names = {2: "Mellinger (firmware)", 6: "OOT Rust geometric"}
    print(f"\nSetting controller: {ctrl_names.get(controller, str(controller))} (type {controller})")
    cf.param.set_value("stabilizer.controller", str(controller))
    time.sleep(0.2)

    # Reset Kalman estimator
    print("Resetting Kalman estimator...")
    cf.param.set_value("kalman.resetEstimation", "1")
    time.sleep(0.1)
    cf.param.set_value("kalman.resetEstimation", "0")

    wait_for_kalman(scf)

    # Takeoff
    print(f"\nTakeoff to {HOVER_HEIGHT:.2f} m over 4 s...")
    hl.takeoff(HOVER_HEIGHT, 4.0)
    print("  Waiting 8 s for climb + estimator stabilization...")
    time.sleep(8.0)

    # Read EKF position to confirm we're hovering
    pos_cfg = LogConfig(name="Pos", period_in_ms=100)
    pos_cfg.add_variable("stateEstimate.x", "float")
    pos_cfg.add_variable("stateEstimate.y", "float")
    pos_cfg.add_variable("stateEstimate.z", "float")
    with SyncLogger(scf, pos_cfg) as logger:
        for entry in logger:
            d = entry[1]
            x, y, z = d["stateEstimate.x"], d["stateEstimate.y"], d["stateEstimate.z"]
            print(f"  Hover position: x={x:+.3f}  y={y:+.3f}  z={z:.3f} m")
            break

    # Execute trajectory (n_laps times; each lap starts from current position)
    for lap in range(1, n_laps + 1):
        print(f"\n--- Lap {lap}/{n_laps}: starting trajectory ---")
        print(f"  Duration: {actual_s:.1f} s at SPEED_SCALE={SPEED_SCALE}")
        hl.start_trajectory(traj_id, SPEED_SCALE, relative_position=True)

        # Log position during flight
        t_end = time.time() + actual_s + 1.5
        with SyncLogger(scf, pos_cfg) as logger:
            for entry in logger:
                d = entry[1]
                x, y, z = d["stateEstimate.x"], d["stateEstimate.y"], d["stateEstimate.z"]
                print(f"  lap {lap}  x={x:+.3f}  y={y:+.3f}  z={z:.3f}          ", end="\r")
                if time.time() >= t_end:
                    break
        print()

        # Small pause between laps
        if lap < n_laps:
            print("  Hovering 2 s between laps...")
            hl.go_to(0.0, 0.0, HOVER_HEIGHT, 0.0, 2.0, relative=True)
            time.sleep(2.5)

    # Land
    print("\nLanding...")
    hl.land(0.0, 3.0)
    time.sleep(4.0)
    hl.stop()
    print("Done.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Spline circle flight via HLC")
    parser.add_argument("--controller", type=int, default=6,
                        help="Controller type: 6=OOT Rust geometric (default), 2=Mellinger")
    parser.add_argument("--laps", type=int, default=1,
                        help="Number of laps to fly (default: 1)")
    parser.add_argument("--uri", default=None,
                        help="Crazyflie URI (default: from environment or radio://0/80/2M/E7E7E7E7E7)")
    args = parser.parse_args()

    uri = args.uri or uri_helper.uri_from_env(default=DEFAULT_URI)
    print(f"Connecting to {uri}...")
    print(f"Controller: {args.controller}  |  Laps: {args.laps}  |  SPEED_SCALE: {SPEED_SCALE}")

    cflib.crtp.init_drivers()
    with SyncCrazyflie(uri, cf=Crazyflie(rw_cache="./cache")) as scf:
        fly_circle(scf, n_laps=args.laps, controller=args.controller)
